- name: Git pull maven compile tomcat deploy
  hosts: all
  become: yes
  tasks:
    - name: check out the repository on the host
      git:
        repo: https://github.com/heiheihang/spring-petclinic.git 
        dest: /home/vagrant/myproject/ 

    - name: package project
      command: cd home/vagrant/myproject && sudo mvn clean package -Dcheckstyle.skip

    - name: run project
      command: ./java -jar ./home/vagrant/myproject/target/*.jar
