- name: Git pull maven compile tomcat deploy
  hosts: all
  become: yes
  tasks:
    - name: check out the repository on the host
      git: repo=https://github.com/heiheihang/spring-petclinic.git dest=/myproject/ accept_hostkey=yes

    - name: package project
      command: ./myproject/mvnw package

    - name: run project
      command: ./java -jar ./myproject/target/*.jar
