- name: Git pull maven compile tomcat deploy
  hosts: all
  become: yes
  tasks:
    - name: check out the repository on the host
      git:
        repo: https://github.com/heiheihang/spring-petclinic.git 
        dest: /home/vagrant/myproject/ 

    - name: package project
      command: sudo mvn -f /home/vagrant/myproject/pom.xml clean package -Dcheckstyle.skip && java -jar /home/vagrant/myproject/target/*.jar

